# Generated by Django 3.2.3 on 2021-05-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кинотеатра')),
                ('description', models.TextField(verbose_name='Описание')),
                ('condition', models.TextField(verbose_name='Условия')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('banner', models.ImageField(upload_to='', verbose_name='Фото верхнего баннера')),
            ],
        ),
        migrations.CreateModel(
            name='SeoParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Главная картинка')),
                ('youtube_link', models.URLField(max_length=100, verbose_name='Ссылка на видео')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seoparameters', verbose_name='SEO блок')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название новости')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Главная картинка')),
                ('youtube_link', models.URLField(max_length=100, verbose_name='Ссылка на видео')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seoparameters', verbose_name='SEO блок')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер зала')),
                ('description', models.TextField(verbose_name='Описание')),
                ('banner', models.ImageField(upload_to='', verbose_name='Верхний баннер')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cinema')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seoparameters', verbose_name='SEO блок')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seoparameters', verbose_name='SEO блок'),
        ),
    ]
