# Generated by Django 3.2.3 on 2021-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210622_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit_ru',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit_uk',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возрастное ограничение'),
        ),
    ]
