# Generated by Django 3.2.3 on 2021-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210529_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(upload_to='', verbose_name='Фото верхнего баннера'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ImageField(upload_to='', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='main_image',
            field=models.ImageField(upload_to='', verbose_name='Главная картинка'),
        ),
    ]
