# Generated by Django 3.2.3 on 2021-06-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210624_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_limit_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age_limit_uk',
        ),
    ]
