# Generated by Django 3.2.3 on 2021-05-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210529_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoparameters',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='seoparameters',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.RenameField(
            model_name='seoparameters',
            old_name='title',
            new_name='seo_title',
        ),
        migrations.RenameField(
            model_name='seoparameters',
            old_name='url',
            new_name='seo_url',
        ),
    ]
