# Generated by Django 3.2.3 on 2021-07-03 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210624_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена обычного билета'),
        ),
        migrations.AlterField(
            model_name='session',
            name='vip_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена VIP-билета'),
        ),
    ]
