# Generated by Django 3.2.3 on 2021-05-30 11:11

import app.models as app_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210530_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Фото верхнего баннера'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=app_models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='main_image',
            field=models.ImageField(upload_to=app_models.get_upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together={('name', 'description', 'condition')},
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('number', 'cinema')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('name', 'description', 'release_date')},
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'published')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('title', 'published')},
        ),
    ]
