# Generated by Django 3.2.3 on 2021-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210530_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='condition_ru',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='condition_uk',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='stock',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stock',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название акции'),
        ),
        migrations.AddField(
            model_name='stock',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название акции'),
        ),
    ]
