# Generated by Django 3.2.3 on 2021-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210601_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoparameters',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoparameters',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seoparameters',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seoparameters',
            name='seo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
