# Generated by Django 3.2.3 on 2021-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210601_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
