# Generated by Django 3.2.3 on 2021-06-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210602_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-published',)},
        ),
    ]
