# Generated by Django 3.2.3 on 2021-06-07 11:00

from django.db import migrations, models
import django_seconds_field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210602_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotational_speed', django_seconds_field.SecondsField(verbose_name='Скорость вращения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
