# Generated by Django 3.2.3 on 2021-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_bannerpage_rotational_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerpage',
            old_name='rotational_speed',
            new_name='news_and_stock_advertices_rotational_speed',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='top_rotational_speed',
            field=models.CharField(choices=[(1, '1c'), (2, '2c'), (3, '3c'), (4, '4c'), (5, '5c'), (6, '6c'), (7, '7c'), (8, '8c'), (9, '9c')], default=1, max_length=5, verbose_name='Скорость вращения'),
            preserve_default=False,
        ),
    ]
