# Generated by Django 3.2.3 on 2021-06-07 15:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210607_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotational_speed', models.CharField(choices=[(1, '1c'), (2, '2c'), (3, '3c'), (4, '4c'), (5, '5c'), (6, '6c'), (7, '7c'), (8, '8c'), (9, '9c')], max_length=5, verbose_name='Скорость вращения')),
                ('backgroung_image', models.ImageField(upload_to=app.models.get_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsAndStockBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotational_speed', models.CharField(choices=[(1, '1c'), (2, '2c'), (3, '3c'), (4, '4c'), (5, '5c'), (6, '6c'), (7, '7c'), (8, '8c'), (9, '9c')], max_length=5, verbose_name='Скорость вращения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BannerPage',
        ),
    ]
