# Generated by Django 3.2.3 on 2021-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210607_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagebanner',
            name='rotational_speed',
            field=models.CharField(choices=[('1', '1c'), ('2', '2c'), ('3', '3c'), ('4', '4c'), ('5', '5c'), ('6', '6c'), ('7', '7c'), ('8', '8c'), ('9', '9c')], max_length=5, verbose_name='Скорость вращения'),
        ),
        migrations.AlterField(
            model_name='newsandstockbanner',
            name='rotational_speed',
            field=models.CharField(choices=[('1', '1c'), ('2', '2c'), ('3', '3c'), ('4', '4c'), ('5', '5c'), ('6', '6c'), ('7', '7c'), ('8', '8c'), ('9', '9c')], max_length=5, verbose_name='Скорость вращения'),
        ),
    ]
