# Generated by Django 3.2.3 on 2021-06-11 07:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
