# Generated by Django 3.2.3 on 2021-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210611_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebarpage',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafebarpage',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafebarpage',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafebarpage',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
