# Generated by Django 3.2.3 on 2021-06-11 10:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_viphallpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebarpage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='viphallpage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_upload_path, verbose_name='Главная картинка'),
        ),
    ]
