# Generated by Django 3.2.3 on 2021-06-14 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_mobileapppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 14, 15, 54, 24, 598967, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='supported_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '3D'), (1, '2D'), (2, 'IMAX')], default=1, max_length=5, verbose_name='Поддерживаемые форматы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название кинотеатра'),
        ),
    ]
