# Generated by Django 3.2.3 on 2021-06-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210614_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('real_position', models.PositiveIntegerField(verbose_name='Реальное местоположение в ряду')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP-место?')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hall')),
            ],
            options={
                'unique_together': {('hall', 'row', 'real_position')},
            },
        ),
    ]
