# Generated by Django 3.2.3 on 2021-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_hallplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallplace',
            name='real_row',
            field=models.PositiveIntegerField(default=-1, verbose_name='Реальный ряд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hallplace',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='hallplace',
            name='row',
            field=models.IntegerField(verbose_name='Ряд'),
        ),
    ]
