# Generated by Django 3.2.3 on 2021-06-11 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.FileField(upload_to='emails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('html',))])),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
